name: Build Kijiji-Scraper using PyInstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python v3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests bs4 pyyaml
    
    - name: Build with PyInstaller
      run: |
        pyinstaller kijiji.py
    
    - uses: actions/upload-artifact@v2
      with:
        name: Release Kijiji.exe
        path: dist/